import 'package:plezy/media/media_backend.dart';
import 'package:plezy/media/media_item.dart';
import 'package:plezy/media/media_kind.dart';
import 'package:plezy/media/media_role.dart';
import 'package:plezy/media/media_version.dart';

/// Canonical backend-neutral [MediaItem] fixture.
///
/// Tests should override only fields relevant to the behavior under test. The
/// defaults deliberately form a valid Plex movie without inventing hierarchy,
/// watch-state, or library metadata that could influence derived getters.
MediaItem testMediaItem({
  String id = 'item-1',
  MediaBackend backend = MediaBackend.plex,
  MediaKind kind = MediaKind.movie,
  String? guid,
  String? title,
  String? titleSort,
  String? summary,
  String? tagline,
  String? originalTitle,
  String? studio,
  int? year,
  String? originallyAvailableAt,
  String? contentRating,
  String? parentId,
  String? parentTitle,
  String? parentThumbPath,
  int? parentIndex,
  int? index,
  String? grandparentId,
  String? grandparentTitle,
  String? grandparentThumbPath,
  String? grandparentArtPath,
  String? thumbPath,
  String? artPath,
  String? clearLogoPath,
  String? backgroundSquarePath,
  int? durationMs,
  int? viewOffsetMs,
  int? viewCount,
  int? lastViewedAt,
  int? leafCount,
  int? viewedLeafCount,
  int? childCount,
  int? addedAt,
  int? updatedAt,
  double? rating,
  double? userRating,
  bool? isFavorite,
  List<String>? genres,
  List<String>? directors,
  List<String>? writers,
  List<String>? producers,
  List<String>? countries,
  List<String>? collections,
  List<String>? labels,
  List<String>? styles,
  List<String>? moods,
  List<MediaRole>? roles,
  List<MediaVersion>? mediaVersions,
  String? libraryId,
  String? libraryTitle,
  String? audioLanguage,
  String? subtitleLanguage,
  int? subtitleMode,
  String? serverId,
  String? serverName,
  String? backendFolderKey,
  Map<String, Object?>? raw,
}) {
  return MediaItem(
    id: id,
    backend: backend,
    kind: kind,
    guid: guid,
    title: title,
    titleSort: titleSort,
    summary: summary,
    tagline: tagline,
    originalTitle: originalTitle,
    studio: studio,
    year: year,
    originallyAvailableAt: originallyAvailableAt,
    contentRating: contentRating,
    parentId: parentId,
    parentTitle: parentTitle,
    parentThumbPath: parentThumbPath,
    parentIndex: parentIndex,
    index: index,
    grandparentId: grandparentId,
    grandparentTitle: grandparentTitle,
    grandparentThumbPath: grandparentThumbPath,
    grandparentArtPath: grandparentArtPath,
    thumbPath: thumbPath,
    artPath: artPath,
    clearLogoPath: clearLogoPath,
    backgroundSquarePath: backgroundSquarePath,
    durationMs: durationMs,
    viewOffsetMs: viewOffsetMs,
    viewCount: viewCount,
    lastViewedAt: lastViewedAt,
    leafCount: leafCount,
    viewedLeafCount: viewedLeafCount,
    childCount: childCount,
    addedAt: addedAt,
    updatedAt: updatedAt,
    rating: rating,
    userRating: userRating,
    isFavorite: isFavorite,
    genres: genres,
    directors: directors,
    writers: writers,
    producers: producers,
    countries: countries,
    collections: collections,
    labels: labels,
    styles: styles,
    moods: moods,
    roles: roles,
    mediaVersions: mediaVersions,
    libraryId: libraryId,
    libraryTitle: libraryTitle,
    audioLanguage: audioLanguage,
    subtitleLanguage: subtitleLanguage,
    subtitleMode: subtitleMode,
    serverId: serverId,
    serverName: serverName,
    backendFolderKey: backendFolderKey,
    raw: raw,
  );
}

/// Season fixture with canonical show linkage.
MediaItem testSeason({
  String id = 'season-1',
  MediaItem? show,
  int index = 1,
  String? title,
  MediaBackend? backend,
  String? serverId,
  String? libraryId,
  int? leafCount,
  int? viewedLeafCount,
}) {
  return testMediaItem(
    id: id,
    backend: backend ?? show?.backend ?? MediaBackend.plex,
    kind: MediaKind.season,
    title: title,
    parentId: show?.id,
    parentTitle: show?.title,
    index: index,
    serverId: serverId ?? show?.serverId,
    serverName: show?.serverName,
    libraryId: libraryId ?? show?.libraryId,
    libraryTitle: show?.libraryTitle,
    leafCount: leafCount,
    viewedLeafCount: viewedLeafCount,
  );
}

/// Episode fixture with canonical show and season linkage.
MediaItem testEpisode({
  String id = 'episode-1',
  MediaItem? show,
  MediaItem? season,
  int index = 1,
  String? title,
  MediaBackend? backend,
  String? serverId,
  String? libraryId,
  int? durationMs,
  int? viewOffsetMs,
  int? viewCount,
  String? originallyAvailableAt,
  List<MediaVersion>? mediaVersions,
}) {
  return testMediaItem(
    id: id,
    backend: backend ?? season?.backend ?? show?.backend ?? MediaBackend.plex,
    kind: MediaKind.episode,
    title: title,
    parentId: season?.id,
    parentTitle: season?.title,
    parentIndex: season?.index,
    index: index,
    grandparentId: show?.id,
    grandparentTitle: show?.title,
    serverId: serverId ?? season?.serverId ?? show?.serverId,
    serverName: season?.serverName ?? show?.serverName,
    libraryId: libraryId ?? season?.libraryId ?? show?.libraryId,
    libraryTitle: season?.libraryTitle ?? show?.libraryTitle,
    durationMs: durationMs,
    viewOffsetMs: viewOffsetMs,
    viewCount: viewCount,
    originallyAvailableAt: originallyAvailableAt,
    mediaVersions: mediaVersions,
  );
}
